apiVersion: zen.cpd.ibm.com/v1
kind: ZenExtension
metadata:
  name: {{ .serviceName }}
spec:
  extensions: |
    [
      {
        "extension_name": "{{ .serviceName }}",
        "details": {
          "upstream_conf": "upstream.conf",
          "location_conf": "nginx.conf"
        }
      }
    ]
  upstream.conf: |
    upstream {{ .upstreamName }} {
      keepalive 32;
      keepalive_timeout 30s;
      keepalive_requests 500;
      server {{ .serviceName }}.{{ .dpPhyLocWorkloadNs }}.svc:{{ .servicePort }};
    }
  nginx.conf: |
    location ~* /{{ .serviceName }}/(.*) {
      proxy_http_version 1.1;
      proxy_set_header Host $host;
      proxy_set_header Connection "";
      proxy_ssl_server_name on;
      proxy_buffering off;
      proxy_pass {{ .serviceUrlScheme }}://{{ .upstreamName }}/$1$is_args$args;
      proxy_pass_header X-Accel-Buffering;
      ##preserve original host on app redirect
      proxy_redirect ~^(https?://[^/]+)?/admin([#/]?.*)$ $scheme://$http_x_original_host/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/admin$2;
      proxy_set_header Accept-Encoding "";
      sub_filter_once off;
      sub_filter_types *;
      sub_filter 'href="/' 'href="/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
      sub_filter "href='/" "href='/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/";
      sub_filter 'src="/' 'src="/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
      sub_filter "src='/" "src='/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/";
      sub_filter 'action="/' 'action="/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
      sub_filter "action='/" "action='/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/";
      sub_filter 'url("/' 'url("/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
      sub_filter "url('/" "url('/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/";
      sub_filter 'window.location="/' 'window.location="/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
      sub_filter "window.location='/" "window.location='/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/";
      sub_filter 'location.href="/' 'location.href="/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
      sub_filter "location.href='/" "location.href='/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/";
      sub_filter '{window.ROOT_PATH}/' '{window.ROOT_PATH}/physical_location/{{ .zenPhysicalLocationName }}/{{ .serviceName }}/';
    }
